module.exports = {
    bot: {
        prefix: ".",
        sahipler: ["360742761856630784"],
        botlar: [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
            ],
        sunucuid: "",
        dtag: "•",
        tag: "",
        hatalog: "",
        komutlog: "",
        footer: " Rencîα ❤️ Falestra",
        status: "dnd",
        icon: "https://cdn.discordapp.com/attachments/746515723580473464/875115076577804349/discowpp.png",
        yassiniri: 10
    },
    roller: {
        bot: "",
        supheli: "",
        kayitsiz: "",
        erkek1: "",
        kiz1: "",
        tagli: "",
        booster: "",
		yetkilistaff: "",
        registerstaff: "",
        cmutestaff: "",
        vmutestaff: "",
        slavestaff: "",
        kickstaff: "",
        banstaff: "",
        kommader: "",
        cmute: "",
        vmute: "",
        cezali: ""
    },
    kanallar: {
        registerchat: "",
        chat: "",
        kurallar: "",
        seslioda: "",
        otorollog: "",
        invitelog: "",
        registerlog: "",
        taglilog: "",
        banlog: "",
        kicklog: "",
        slavelog: "",
        cmutelog: "",
        vmutelog: "",
        generallog: "",
        guardlog: "",
        urlguardlog: "",
        onerisikayetlog: "",
        welcome1: "",
        welcome2: "",
        welcome3: "",
        welcome4: "",
        welcome5: ""
    },
    emojiler: {
        discow000: "",
        discow001: "",
        discow002: "",
        discow003: "",
        discow004: "",
        discow005: "",
        discow006: "",
        discow007: "",
        discow008: "",
        discow009: "",
        discow_acik: "",
        discow_yetkili: "",
        discow_kapali: "",
        discow_video: "",
        discow_kamera: "",
        discow_ses: "",
        discow_sohbet: "",
        discow_kurallar: "",
        discow_carpi: "",
        discow_tik: "",
        discow_kulaklik: "",
        discow_belge2: "",
        discow_sayac: "",
        discow_belge1: "",
        discow_kristal: "",
        discow_zil: "",
        discow_boost: "",
        discow_ok: "",
        discow_kilit: "",
        discow_dolu_son: "",
        discow_bos_bas: "",
        discow_dolu_bas: "",
        discow_bos_son: "",
        discow_dolu_orta: "",
        discow_bos_orta: ""
    }
}